# Motorrak: OUTPUT_A, OUTPUT_B, OUTPUT_C, OUTPUT_D
# Sentsoreak: INPUT_1, INPUT_2, INPUT_3, INPUT_4

# MOTOR HANDIAK
#   Mugimendu 1.go ezker motor HANDIA: M1EMH
#   Mugimendu 2. ezker motor HANDIA: M2EZMH
#   Mugimendu 1.go eskuin motor HANDIA: M1ESMH
#   Mugimendu 2. eskuin motor HANDIA: M2ESMH
#
#   Osagarri 1. motor HANDIA: O1MH
#   Osagarri 2. motor HANDIA: O2MH
#   Osagarri 3. motor HANDIA: O3MH
#   Osagarri 4. motor HANDIA: O4MH

# MOTOR TXIKIAK
#   Mugimendu 1.go ezker motor TXIKIA: M1EMT
#   Mugimendu 2. ezker motor TXIKIA: M2EZMT
#   Mugimendu 1.go eskuin motor TXIKIA: M1ESMT
#   Mugimendu 2. eskuin motor TXIKIA: M2ESMT
#
#   Osagarri 1. motor TXIKIA: O1MT
#   Osagarri 2. motor TXIKIA: O2MT
#   Osagarri 3. motor TXIKIA: O3MT
#   Osagarri 4. motor TXIKIA: O4MT

# SENTSOREAK
#   Biraketa: GS
#   Ultrasoinu: US
#   Argi / Kolore: CS

OUTPUT_A: M1EMH
OUTPUT_B:
OUTPUT_C:
OUTPUT_D: M1ESMH

INPUT_1:
INPUT_2: US
INPUT_3: GS
INPUT_4:

#
#motor_handiak:
#  mugimendu_motorrak:
#    lehengoa_ezkerra: OUTPUT_A
#    lehenengoa_eskuina: OUTPUT_D
#    bigarrena_ezkerra:
#    bigarrena_eskuina:
#
#  osagarriak_mugitzeko_motorrak:
#    lehenengoa:
#    bigarrena:
#    hirugarrena:
#    laugarrena:
#
#motor_txikiak:
#  mugimendu_motorrak:
#    lehengoa_ezkerra: 
#    lehenengoa_eskuina: 
#    bigarrena_ezkerra:
#    bigarrena_eskuina:
#
#  osagarriak_mugitzeko_motorrak:
#    lehenengoa:
#    bigarrena:
#    hirugarrena:
#    laugarrena:
#  
#sentsoreak:
#  biraketa:
#  ultrasoinu:
#