teklatua:
  ros__parameters:
    abiadura: 25.0

mando:
  ros__parameters:
    abiadura: 25.0
    threshold: 2.0

mugimendu_motorrak:
  ros__parameters:
    abiadura: 25.0

joy:
  ros__parameters:
    deadzone: 0.25
    autorepeat_rate: 5.0
