/**:
  ros__parameters:
    abiadura: 30.0

#teklatua:
  #ros__parameters:
    #abiadura: 50.0

mando:
  ros__parameters:
    #abiadura: 50.0
    threshold: 2.0

mugimendu_motorrak:
  ros__parameters:
    #abiadura: 50.0
    motor_alderantzikatuak: true

joy:
  ros__parameters:
    deadzone: 0.25
    autorepeat_rate: 5.0

zuzen_objektuarenganaino:
  ros__parameters:
    eten_distantzia: 0.15
    desbideratzeak_zuzendu: True
    kp: 5.31
    seinalea_gorde: True

fuzzy_mugimendua:
  ros__parameters:
    eten_distantzia: 0.15
    kontrol_mota: "nbs"
    ikas_modua: False
    seinalea_gorde: True

fuzzy_nn_mugimendua:
  ros__parameters:
    modeloa: "/home/javierac/eduros2_lego/ws/install/fuzzy_control/share/ikas_datuak/model.pt"
    eten_distantzia: 0.15
    factor: 1.0
    kontrol_mota: "nbs"
    seinalea_gorde: True
