/**:
  ros__parameters:
    abiadura: 30.0

#teklatua:
  #ros__parameters:
    #abiadura: 50.0

mando:
  ros__parameters:
    #abiadura: 50.0
    threshold: 2.0

mugimendu_motorrak:
  ros__parameters:
    #abiadura: 50.0
    motor_alderantzikatuak: true

joy:
  ros__parameters:
    deadzone: 0.25
    autorepeat_rate: 5.0

zuzen_objektuarenganaino:
  ros__parameters:
    eten_distantzia: 0.15
    desbideratzeak_zuzendu: 1
    kp: 9.0
    seinalea_gorde: "True"

fuzzy_mugimendua:
  ros__parameters:
    kontrol_mota: "nbs"
    ikas_modua: "True"

fuzzy_nn_mugimendua:
  ros__parameters:
    kontrol_mota: "nbs"
    ikas_modua: "False"
